# Generated by Django 3.1.5 on 2021-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=20, unique='True')),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=47, null=True)),
            ],
        ),
    ]
