# Generated by Django 3.1.5 on 2021-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=20, unique='True')),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=49, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catego', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('press', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customname', models.CharField(max_length=20)),
                ('customemail', models.CharField(default='', max_length=60, null=True)),
                ('customphone', models.CharField(default='', max_length=15, null=True)),
                ('customaddress', models.CharField(default='', max_length=100, null=True)),
                ('unitname', models.CharField(default='', max_length=100)),
                ('unitnum', models.IntegerField(default=0)),
                ('unitprice', models.IntegerField(default=0)),
            ],
        ),
    ]
