# Generated by Django 3.1.7 on 2021-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210314_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=20, unique='True'),
        ),
    ]
