# Generated by Django 3.1.5 on 2021-05-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210505_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nowtime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
