# Generated by Django 3.1.7 on 2021-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210310_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passw',
            field=models.DateField(),
        ),
    ]
