# Generated by Django 3.1.5 on 2021-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210317_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=19),
        ),
    ]
