# Generated by Django 3.1.5 on 2021-05-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210501_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cutomname',
            new_name='customname',
        ),
    ]
