# Generated by Django 3.1.7 on 2021-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210310_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pas2222',
            field=models.DateField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='passw',
            field=models.CharField(max_length=20),
        ),
    ]
