# Generated by Django 3.1.5 on 2021-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210509_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nowtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
