# Generated by Django 3.1.7 on 2021-03-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210310_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='pas2222',
            new_name='pas2232',
        ),
    ]
