# Generated by Django 3.1.5 on 2021-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210509_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nowtime',
            field=models.CharField(max_length=20),
        ),
    ]
