# Generated by Django 3.1.7 on 2021-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210310_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='account',
        ),
        migrations.RemoveField(
            model_name='member',
            name='passw',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, default=1996, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
