# Generated by Django 3.1.5 on 2021-05-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210501_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customaddress',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customemail',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customname',
            field=models.CharField(max_length=20, unique='True'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customphone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
