# Generated by Django 3.1.7 on 2021-03-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210310_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='pas2232',
            new_name='pas32',
        ),
    ]
