# Generated by Django 3.1.5 on 2021-05-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210502_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customname',
            field=models.CharField(max_length=20),
        ),
    ]
