# Generated by Django 3.1.7 on 2021-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210509_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customname', models.CharField(max_length=20)),
                ('customaccount', models.CharField(max_length=20)),
                ('salename', models.CharField(max_length=20)),
                ('salenum', models.IntegerField(default=0)),
                ('saleprice', models.IntegerField(default=0)),
            ],
        ),
    ]
