# Generated by Django 3.1.7 on 2021-03-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210310_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pas32',
        ),
        migrations.AddField(
            model_name='member',
            name='pas3',
            field=models.DateField(default=-1999),
            preserve_default=False,
        ),
    ]
