# Generated by Django 3.1.5 on 2021-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderview'),
    ]

    operations = [
        migrations.CreateModel(
            name='beefview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
    ]
