# Generated by Django 3.1.7 on 2021-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210310_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='pas3',
        ),
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.CharField(default=6, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='passw123',
            field=models.CharField(default=800, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
    ]
