# Generated by Django 3.1.7 on 2021-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210310_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='passw123',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
