# Generated by Django 3.1.5 on 2021-05-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_beefview'),
    ]

    operations = [
        migrations.CreateModel(
            name='agaricusview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='chickenview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lambview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pigview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='seafoodview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vegetableview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salename', models.CharField(max_length=20)),
                ('saleprice', models.IntegerField(default=0)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
    ]
