# Generated by Django 3.1.5 on 2021-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_agaricusview_chickenview_lambview_pigview_seafoodview_vegetableview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100, unique='True'),
        ),
    ]
